### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by hasecilu**
Still not finished but it's on its way.

In some strings it's used `forward shoulder` alongside `aft shoulder` and in other strings is `fore shoulder` alongside `aft shoulder`. Is `forward shoulder` and `fore shoulder` equivalent? Could be `forward shoulder` be replaced by `fore shoulder`?

I noticed the ts file was updated to version 2.1 and this changed tabs in all file, I hope this changes are not breaking anything. I used Qt Linguist 5.15.6

### CODE REVIEW

**Comment by davesrocketshop** [comment]
While I appreciate the work, this is not how translations are done.

Translations are done using the Crowdin website (https://crowdin.com/project/freecad) and integrated into the project using an update script. Your translations would be over written on the first update.

You can read more on the process starting here https://wiki.freecadweb.org/Localisation

**Comment by davesrocketshop** [comment]
Not merging as changes would be overwritten on next translation update

**Comment by hasecilu** [comment]
Hello, I have uploaded my translations at crowdin, I didn't know that Rocket WB was in crowdin, it could be useful to have a `CONTRIBUTING.md` file with a link to [FreeCAD-addons](https://crowdin.com/project/freecad-addons), this way people don't get confused. Other external WB are not in crowdin and translations are done via github so I get confused.

**Comment by davesrocketshop** [comment]
Valid point. Crowdin is the recommendation for external workbenches, but I have no idea how many actually do that. I will ad a CONTRIBUTING.md document as you suggested.

Sorry for the confusion. Your efforts are definitely appreciated.

**Pull request closed without merging**
